name = "James"
uuid = "1255bd81-5eaa-404b-95a4-4076c074fc4c"
version = "0.1.0"
authors = ["m410y <m410y@proton.me>"]

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JamesCore = "979fc264-f091-4d46-bc40-ce8d18beab5d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
P4P = "22628b5c-e01d-4582-92b9-755789d4ce9a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SFRM = "c7668fac-7a56-4ae9-9efd-32dbb1c1241a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CoordinateTransformations = "0.6.4"
DataFrames = "1.8.1"
DifferentiationInterface = "0.7.13"
ForwardDiff = "1.3.1"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.12.0"
Optimization = "5.3.0"
OptimizationOptimJL = "0.4.8"
Reexport = "1.2.2"
Rotations = "1.7.1"
Statistics = "1.11.1"
Unitful = "1.25.1"
